Get http://localhost:3000/articles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoieW9hdiIsImlhdCI6MTYyOTExMjU3NH0.TvpRgM2PM19s3smJpDfZyVA0Pl7Wjpy489bnUo4jCF0
###
POST http://localhost:3000/login
Content-Type: application/json

{
"username": "adminw"
}

###
Get http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MjkyNzUyNTh9.HbMh2oiN-p70Q9V-A5yBZHy8CJ59zL-iaOaLcxj4tIg

###
Get http://localhost:3000/echo?msg=fdasdf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MjkyNzUyNTh9.HbMh2oiN-p70Q9V-A5yBZHy8CJ59zL-iaOaLcxj4tIg

###
Get http://localhost:3000/array
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MjkyNzUyNTh9.HbMh2oiN-p70Q9V-A5yBZHy8CJ59zL-iaOaLcxj4tIg

###
Get http://localhost:3000/array/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MjkyNzUyNTh9.HbMh2oiN-p70Q9V-A5yBZHy8CJ59zL-iaOaLcxj4tIg
###
POST http://localhost:3000/array
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MjkyODY3NTN9.hpOQR16yZijBDlgu3vToiplu7B60rNTLIADrX-mVQ-s 
Content-Type: application/json

{
"value": 11
}

###
PUT  http://localhost:3000/array/2
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MjkyNzU0NDh9.STxW8nxpeVX5g-KLoplU5LlJNgkjsxBp0ZbZKjgjwg4
Content-Type: application/json

{
"value": 99
}

###
DELETE  http://localhost:3000/array
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MjkyNzU0NDh9.STxW8nxpeVX5g-KLoplU5LlJNgkjsxBp0ZbZKjgjwg4

###
DELETE  http://localhost:3000/array/1
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MjkyNzU0NDh9.STxW8nxpeVX5g-KLoplU5LlJNgkjsxBp0ZbZKjgjwg4

