

POST http://localhost:3000/login
Content-Type: application/json

{
"username": "admin2"
}

###
Get http://localhost:3000/api/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4yIiwiaWF0IjoxNjI5ODg3NzkyfQ.61CJghi7X9duGCcbRCfGdwo2V7XF8uQhHjwuuIrLWvM

###
Get http://localhost:3000/api/echo?msg=hello
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MjkyNzUyNTh9.HbMh2oiN-p70Q9V-A5yBZHy8CJ59zL-iaOaLcxj4tIg

###
Get http://localhost:3000/api/array
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MjkyNzUyNTh9.HbMh2oiN-p70Q9V-A5yBZHy8CJ59zL-iaOaLcxj4tIg

###
Get http://localhost:3000/api/array/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2Mjk3ODQ1OTZ9.GaweV2l_rJ5W0Qd8P3-dRbgR1oQF29shUmH_JeHUkJU
###
POST http://localhost:3000/api/array
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MjkyODY3NTN9.hpOQR16yZijBDlgu3vToiplu7B60rNTLIADrX-mVQ-s 
Content-Type: application/json

{
"value": 314
}

###
PUT  http://localhost:3000/api/array/1
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4yIiwiaWF0IjoxNjI5ODg3ODU0fQ.Obc_HI541HhTcAvus6nm65RQP7jNl7jrRBL6oUm3Zsw
Content-Type: application/json

{
"value": 21
}

###
DELETE  http://localhost:3000/api/array
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4xIiwiaWF0IjoxNjI5NzkyNzUzfQ.PowpGUailHGAgS1H6LThKPo49eZics0xpU_jHwK250k

###
DELETE  http://localhost:3000/api/array/1
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4xIiwiaWF0IjoxNjI5NzkyNzUzfQ.PowpGUailHGAgS1H6LThKPo49eZics0xpU_jHwK250k

