

POST http://localhost:3000/login
Content-Type: application/json

{
"username": "admin"
}

###
Get http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2Mjk3ODQ1OTZ9.GaweV2l_rJ5W0Qd8P3-dRbgR1oQF29shUmH_JeHUkJU

###
Get http://localhost:3000/echo?msg=fdasdf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MjkyNzUyNTh9.HbMh2oiN-p70Q9V-A5yBZHy8CJ59zL-iaOaLcxj4tIg

###
Get http://localhost:3000/array
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MjkyNzUyNTh9.HbMh2oiN-p70Q9V-A5yBZHy8CJ59zL-iaOaLcxj4tIg

###
Get http://localhost:3000/array/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2Mjk3ODQ1OTZ9.GaweV2l_rJ5W0Qd8P3-dRbgR1oQF29shUmH_JeHUkJU
###
POST http://localhost:3000/array
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MjkyODY3NTN9.hpOQR16yZijBDlgu3vToiplu7B60rNTLIADrX-mVQ-s 
Content-Type: application/json

{
"value": 312
}

###
PUT  http://localhost:3000/array/3
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2Mjk4MDgxODJ9.9gkfY3eE5stQf8tAtXUVtRFBjiz7Bgzwcua-XtqfzGY
Content-Type: application/json

{
"value": 10
}

###
DELETE  http://localhost:3000/array
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4xIiwiaWF0IjoxNjI5NzkyNzUzfQ.PowpGUailHGAgS1H6LThKPo49eZics0xpU_jHwK250k

###
DELETE  http://localhost:3000/array/32121
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4xIiwiaWF0IjoxNjI5NzkyNzUzfQ.PowpGUailHGAgS1H6LThKPo49eZics0xpU_jHwK250k

